<?xml version="1.0"?>
<package format="3">
  <name>video_stream_opencv</name>
  <version>1.1.6</version>

  <description>
    The video_stream_opencv package contains a node to publish a video stream (the protocols that
    opencv supports are supported, including rtsp, webcams on /dev/video and video files) in ROS image topics, it supports camera info and basic image flipping (horizontal, vertical or both) capabilities, also adjusting publishing rate.
  </description>

  <maintainer email="Sammy.Pfeiffer@student.uts.edu.au">Sammy Pfeiffer</maintainer>
  <author>Sammy Pfeiffer</author>

  <url type="website">http://www.ros.org/wiki/video_stream_opencv</url>
  <url type="development">https://github.com/ros-drivers/video_stream_opencv</url>
  <url type="bugtracker">https://github.com/ros-drivers/video_stream_opencv/issues</url>

  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>cv_bridge</build_depend>
  <build_depend>image_transport</build_depend>
  <build_depend>camera_info_manager</build_depend>
  <build_depend>dynamic_reconfigure</build_depend>
  <build_depend>nodelet</build_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>sensor_msgs</build_depend>

  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>image_transport</exec_depend>
  <exec_depend>camera_info_manager</exec_depend>
  <exec_depend>dynamic_reconfigure</exec_depend>
  <exec_depend>nodelet</exec_depend>
  <exec_depend>roscpp</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>

  <test_depend>rostest</test_depend>
  <test_depend>rostopic</test_depend>
  <test_depend>libgstrtspserver-1.0-dev</test_depend>
  <test_depend>gstreamer1.0-plugins-ugly</test_depend>
  <test_depend>gstreamer1.0-libav</test_depend>
  <test_depend>gstreamer1.0-rtsp</test_depend>
  <test_depend condition="$ROS_PYTHON_VERSION == 2">python-gi</test_depend>
  <test_depend condition="$ROS_PYTHON_VERSION == 3">python3-gi</test_depend>
  <test_depend condition="$ROS_PYTHON_VERSION == 2">python-gst-1.0</test_depend>

  <export>
    <nodelet plugin="${prefix}/nodelet_plugins.xml"/>
  </export>
</package>
