name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        env:
          - ROS_DISTRO: noetic
            ROS_REPO: main
            CMAKE_ARGS: -DCMAKE_BUILD_TYPE=RelWithDebInfo
          - ROS_DISTRO: noetic
            ROS_REPO: testing
            CMAKE_ARGS: -DCMAKE_BUILD_TYPE=RelWithDebInfo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ros-industrial/industrial_ci@master
        env: ${{ matrix.env }}
